spring:
  thymeleaf:
    cache: false
    check-template-location: false
    enabled: true
    prefix: classpath:/static/templates
    suffix: .html
    view-names: /html/*

slack:
  webhook-url: https://hooks.slack.com/services/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